### ISSUE TITLE
Any plan on releasing Training code ? , or just a model with speech ?

### ISSUE THREAD

**Issue by manmay-nakhashi** [haoheliu/SemantiCodec-inference#1]

**Comment by haoheliu** [comment]
Sorry I personally do not have bandwidth for now so might not be released in the near future. The training code will be somehow similar to https://github.com/haoheliu/AudioLDM-training-finetuning so I would suggest building upon this code base if interested.

**Comment by manmay-nakhashi** [comment]
thanks :)
