### ISSUE TITLE
Generation speed

### ISSUE THREAD

**Issue by yaotingwangofficial** [haoheliu/SemantiCodec-inference#5]
Thanks for your cool work, I tried some samples and the performance is really good and love the token-saving. But seems the decoding process is too low compared to others, is there any possible method to accelerate the decoding into <1s for decoding around 10s speech?  Many thanks!

**Comment by haoheliu** [comment]
@yaotingwangofficial That might need some extra optimization on the engineering side. Since this is only a research-based project, so I do not conduct thorough optimization on the inference speed. You are most welcome to contribute on that if you want of course.

**Comment by yaotingwangofficial** [comment]
Thanks!
